# Generated by Django 5.0.6 on 2024-06-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=80)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("emergency_contact_name", models.CharField(max_length=80)),
                ("relationship", models.CharField(max_length=50)),
                ("emergency_contact_phone", models.CharField(max_length=15)),
                ("medical_conditions", models.TextField(blank=True, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("current_medications", models.TextField(blank=True, null=True)),
                ("previous_injuries", models.TextField(blank=True, null=True)),
                ("fitness_goals", models.TextField(blank=True, null=True)),
                (
                    "fitness_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("liability_waiver", models.BooleanField(default=False)),
                ("terms_conditions", models.BooleanField(default=False)),
                ("privacy_policy", models.BooleanField(default=False)),
                ("marketing_consent", models.BooleanField(default=False)),
                (
                    "preferred_workout_times",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("referred_by", models.CharField(blank=True, max_length=80, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
