# Generated by Django 5.0.6 on 2024-06-27 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="admission",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="admission",
            name="fitness_level",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="admission",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="admission",
            name="membership_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="admission",
            name="payment_method",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="admission",
            name="preferred_workout_times",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="admission",
            name="referred_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="admission",
            name="relationship",
            field=models.CharField(max_length=20),
        ),
    ]
