# Generated by Django 5.0.6 on 2024-06-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_admission_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="profile_image",
        ),
    ]
