# Generated by Django 5.0.6 on 2024-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_admission_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="preferred_workout_times",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
