# Generated by Django 5.0.6 on 2024-06-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_admission_preferred_workout_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
