# Generated by Django 5.0.6 on 2024-06-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_admission_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="profile_image",
        ),
    ]
