# Generated by Django 5.0.6 on 2024-07-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_remove_admission_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
