# Generated by Django 5.0.6 on 2024-07-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_remove_admission_liability_waiver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="preferred_workout_times",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="referred_by",
        ),
        migrations.AddField(
            model_name="admission",
            name="admission_fee",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="pay_now",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="trainer_duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="trainer_fee",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="trainer_required",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
