# Generated by Django 5.0.6 on 2024-07-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_remove_admission_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_from", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("admission_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "personal_trainer_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "gym_type_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("next_payment_date", models.DateField()),
                ("in_words", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
