# Generated by Django 5.0.6 on 2024-07-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_receipt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Receipt",
        ),
    ]
