# Generated by Django 5.0.6 on 2024-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_receipt_nextpaymentdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="nextPaymentDate",
            field=models.DateField(),
        ),
    ]
