# Generated by Django 5.0.6 on 2024-07-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_receipt_nextpaymentdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="nextPaymentDate",
            new_name="next_payment_date",
        ),
        migrations.AlterField(
            model_name="receipt",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="gym_type_fee",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="receipt",
            name="in_words",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="slno",
            field=models.CharField(max_length=10),
        ),
    ]
