# Generated by Django 5.0.6 on 2024-07-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_rename_nextpaymentdate_receipt_next_payment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="id",
        ),
        migrations.AlterField(
            model_name="receipt",
            name="admission_fee",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="gym_type_fee",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="personal_trainer_fee",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="slno",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total_amount",
            field=models.ImageField(upload_to=""),
        ),
    ]
