# Generated by Django 5.0.6 on 2024-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_admission_form_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="form_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
